version: "2"
services:  
  master:
    image: intachompoo/jenkins-master:2.1
    container_name: jenkins_master
    ports:
      - "50000:50000"  
      - "8080:8080"
    environment:
      #JNLP_PROTOCOL_OPTS: "-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=false"
      JAVA_OPTS: "-Djava.awt.headless=true"  
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked 
    volumes:
      - jenkins-master:/var/jenkins_home
    networks:
      - jenkins-net

  worker:
    image: intachompoo/jenkins-slave
    container_name: jenkins_slave
    depends_on:
      - master
    environment:
      JENKINS_URL: "http://master:8080"
     # JENKINS_TUNNEL: "master:50000"
      JENKINS_SECRET: "1833787fd9283e59d78044133952ac0d3a76337c5f821684a10e80c9c2e34436"
      JENKINS_AGENT_NAME: "jnlp-docker-slave"
      JENKINS_AGENT_WORKDIR: "/home/jenkins/agent"
    volumes:
      - jenkins-worker:/var/jenkins_home/worker
    networks:
      - jenkins-net

volumes:
  jenkins-master:
  jenkins-worker:
networks:
  jenkins-net:
