version: '2'
services:
    postgres:
      image: postgres:9.5
      restart: always
      environment:
       - "POSTGRES_USER=postadm"
       - "POSTGRES_PASSWORD=postadm"
       - "POSTGRES_DB=sonar"
      volumes:
       - postgres-db-data:/var/lib/postgresql/data
      networks:
        - jenkins-net

    gogs:
      image: gogs/gogs
      restart: always
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - postgres
      environment:
       - "RUN_CROND=true"
      networks:
        - jenkins-net
      volumes:
       - gogs-data:/data
      depends_on:
       - postgres

    sonarqube:
      image: sonarqube
      ports:
       - "9000:9000"
      networks:
       - sonarnet
      environment:
       SONARQUBE_JDBC_USERNAME: postadm
       SONARQUBE_JDBC_PASSWORD: postadm
       SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
       # - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      volumes:
       #- sonarqube_conf:/opt/sonarqube/conf
       - sonarqube_data:/opt/sonarqube/data
       #- sonarqube_extensions:/opt/sonarqube/extensions
       - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      depends_on:
       - postgres
      networks:
       - jenkins-net


volumes:
  postgres-db-data:
  gogs-data:
  sonarqube_data:
  sonarqube_bundled-plugins:
networks:
  jenkins-net:

